spring:
  application:
    name: libraryapi
  profiles:
    active: production
  output:
    ansi:
      enabled: always

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5434/librarydb}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
        hibernate:
            format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

springdoc:
  override-with-generic-response: false

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level:
    root: warn
    io.github.victormacedov: trace
    org.springframework.web: debug
    org.springframework.security: trace

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

#Production profile
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false